### ISSUE TITLE
Add a role based authentification

### ISSUE THREAD

**Issue by rth** [b2b-ray/multifactor_analysis#2]
Using web2py's internal authentification system someone needs to setup a role based authentification for multifactor_analysis tool. 

There should be a group root with full access to everything.
Then for every project there should be a role  project_leader with full access to all studies for this project.
Finaly for every study there should be 3 roles
- editor - read, write access to everything, but cannot delete studies and categories
- user - ro access only to Setup, rw to Dataset and Analysis
- visitor - read access to everything

**Comment by denys-zarubin** [comment]
oks

**Comment by rth** [comment]
Closing as outdated.
